name: CI-CD Integration/w Github Workflow

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        node-version: [ '14.18.2' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Static analysis
        run: |
          echo "Running ESLint static analysis"
          npm run lint
          echo "Running TypeScript static analysis"
          npm run check:typings
          echo "Running production build"
          npm run build:prod


      - name: Webpack Build
        run: |
          echo "Running production build"
          npm run build:prod

  security:
    name: Security Scan
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SAST scan
        uses: AppThreat/sast-scan-action@v1.0.0
        with:
          type: nodejs

      - name: Run SCA scan
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          languages: ${{ matrix.node-version }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deployment:
    name: Deploy to Dev
    needs: [ build, security ]
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHOLY_FRONTEND }}'
          channelId: live
          projectId: sholy-frontend
